(cl:defpackage arm_control-srv
  (:use )
  (:export
   "SOLVEFKPOSE"
   "<SOLVEFKPOSE-REQUEST>"
   "SOLVEFKPOSE-REQUEST"
   "<SOLVEFKPOSE-RESPONSE>"
   "SOLVEFKPOSE-RESPONSE"
   "SOLVEIKPOSE"
   "<SOLVEIKPOSE-REQUEST>"
   "SOLVEIKPOSE-REQUEST"
   "<SOLVEIKPOSE-RESPONSE>"
   "SOLVEIKPOSE-RESPONSE"
  ))

