; Auto-generated. Do not edit!


(cl:in-package arm_control-msg)


;//! \htmlinclude SetPoseGoal.msg.html

(cl:defclass <SetPoseGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type arm_control-msg:Pose
    :initform (cl:make-instance 'arm_control-msg:Pose))
   (eps
    :reader eps
    :initarg :eps
    :type cl:float
    :initform 0.0))
)

(cl:defclass SetPoseGoal (<SetPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_control-msg:<SetPoseGoal> is deprecated: use arm_control-msg:SetPoseGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <SetPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_control-msg:goal-val is deprecated.  Use arm_control-msg:goal instead.")
  (goal m))

(cl:ensure-generic-function 'eps-val :lambda-list '(m))
(cl:defmethod eps-val ((m <SetPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_control-msg:eps-val is deprecated.  Use arm_control-msg:eps instead.")
  (eps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetPoseGoal>) ostream)
  "Serializes a message object of type '<SetPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'eps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetPoseGoal>) istream)
  "Deserializes a message object of type '<SetPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'eps) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetPoseGoal>)))
  "Returns string type for a message object of type '<SetPoseGoal>"
  "arm_control/SetPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetPoseGoal)))
  "Returns string type for a message object of type 'SetPoseGoal"
  "arm_control/SetPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetPoseGoal>)))
  "Returns md5sum for a message object of type '<SetPoseGoal>"
  "20235d062a0a825673e71bb666e5bec7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetPoseGoal)))
  "Returns md5sum for a message object of type 'SetPoseGoal"
  "20235d062a0a825673e71bb666e5bec7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetPoseGoal>)))
  "Returns full string definition for message of type '<SetPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%arm_control/Pose goal~%float64 eps~%~%================================================================================~%MSG: arm_control/Pose~%float64 x~%float64 y~%float64 z~%float64[] rotx~%float64[] roty~%float64[] rotz~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetPoseGoal)))
  "Returns full string definition for message of type 'SetPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%arm_control/Pose goal~%float64 eps~%~%================================================================================~%MSG: arm_control/Pose~%float64 x~%float64 y~%float64 z~%float64[] rotx~%float64[] roty~%float64[] rotz~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetPoseGoal
    (cl:cons ':goal (goal msg))
    (cl:cons ':eps (eps msg))
))
