// Auto-generated. Do not edit!

// (in-package arm_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Pose = require('./Pose.js');

//-----------------------------------------------------------

class SetPoseFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.currentPose = null;
      this.error = null;
      this.time = null;
    }
    else {
      if (initObj.hasOwnProperty('currentPose')) {
        this.currentPose = initObj.currentPose
      }
      else {
        this.currentPose = new Pose();
      }
      if (initObj.hasOwnProperty('error')) {
        this.error = initObj.error
      }
      else {
        this.error = 0.0;
      }
      if (initObj.hasOwnProperty('time')) {
        this.time = initObj.time
      }
      else {
        this.time = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SetPoseFeedback
    // Serialize message field [currentPose]
    bufferOffset = Pose.serialize(obj.currentPose, buffer, bufferOffset);
    // Serialize message field [error]
    bufferOffset = _serializer.float64(obj.error, buffer, bufferOffset);
    // Serialize message field [time]
    bufferOffset = _serializer.float64(obj.time, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SetPoseFeedback
    let len;
    let data = new SetPoseFeedback(null);
    // Deserialize message field [currentPose]
    data.currentPose = Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [error]
    data.error = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [time]
    data.time = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Pose.getMessageSize(object.currentPose);
    return length + 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'arm_control/SetPoseFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '57a46cd82a7bce3b86dc2d8131f7b485';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    arm_control/Pose currentPose
    float64 error
    float64 time
    
    ================================================================================
    MSG: arm_control/Pose
    float64 x
    float64 y
    float64 z
    float64[] rotx
    float64[] roty
    float64[] rotz
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SetPoseFeedback(null);
    if (msg.currentPose !== undefined) {
      resolved.currentPose = Pose.Resolve(msg.currentPose)
    }
    else {
      resolved.currentPose = new Pose()
    }

    if (msg.error !== undefined) {
      resolved.error = msg.error;
    }
    else {
      resolved.error = 0.0
    }

    if (msg.time !== undefined) {
      resolved.time = msg.time;
    }
    else {
      resolved.time = 0.0
    }

    return resolved;
    }
};

module.exports = SetPoseFeedback;
