// Auto-generated. Do not edit!

// (in-package arm_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Pose = require('./Pose.js');

//-----------------------------------------------------------

class SetPoseGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal = null;
      this.eps = null;
    }
    else {
      if (initObj.hasOwnProperty('goal')) {
        this.goal = initObj.goal
      }
      else {
        this.goal = new Pose();
      }
      if (initObj.hasOwnProperty('eps')) {
        this.eps = initObj.eps
      }
      else {
        this.eps = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SetPoseGoal
    // Serialize message field [goal]
    bufferOffset = Pose.serialize(obj.goal, buffer, bufferOffset);
    // Serialize message field [eps]
    bufferOffset = _serializer.float64(obj.eps, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SetPoseGoal
    let len;
    let data = new SetPoseGoal(null);
    // Deserialize message field [goal]
    data.goal = Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [eps]
    data.eps = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Pose.getMessageSize(object.goal);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'arm_control/SetPoseGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '20235d062a0a825673e71bb666e5bec7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    arm_control/Pose goal
    float64 eps
    
    ================================================================================
    MSG: arm_control/Pose
    float64 x
    float64 y
    float64 z
    float64[] rotx
    float64[] roty
    float64[] rotz
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SetPoseGoal(null);
    if (msg.goal !== undefined) {
      resolved.goal = Pose.Resolve(msg.goal)
    }
    else {
      resolved.goal = new Pose()
    }

    if (msg.eps !== undefined) {
      resolved.eps = msg.eps;
    }
    else {
      resolved.eps = 0.0
    }

    return resolved;
    }
};

module.exports = SetPoseGoal;
