// Generated by gencpp from file arm_control/SetJointGoal.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SETJOINTGOAL_H
#define ARM_CONTROL_MESSAGE_SETJOINTGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct SetJointGoal_
{
  typedef SetJointGoal_<ContainerAllocator> Type;

  SetJointGoal_()
    : goal()
    , eps(0.0)  {
    }
  SetJointGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , eps(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _goal_type;
  _goal_type goal;

   typedef double _eps_type;
  _eps_type eps;





  typedef boost::shared_ptr< ::arm_control::SetJointGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::SetJointGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointGoal_

typedef ::arm_control::SetJointGoal_<std::allocator<void> > SetJointGoal;

typedef boost::shared_ptr< ::arm_control::SetJointGoal > SetJointGoalPtr;
typedef boost::shared_ptr< ::arm_control::SetJointGoal const> SetJointGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::SetJointGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::SetJointGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control::SetJointGoal_<ContainerAllocator1> & lhs, const ::arm_control::SetJointGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal &&
    lhs.eps == rhs.eps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control::SetJointGoal_<ContainerAllocator1> & lhs, const ::arm_control::SetJointGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::SetJointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "381aec3abfcdd7a58cb867cc755f1ea1";
  }

  static const char* value(const ::arm_control::SetJointGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x381aec3abfcdd7a5ULL;
  static const uint64_t static_value2 = 0x8cb867cc755f1ea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::SetJointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/SetJointGoal";
  }

  static const char* value(const ::arm_control::SetJointGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::SetJointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"float64[] goal\n"
"float64 eps\n"
;
  }

  static const char* value(const ::arm_control::SetJointGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::SetJointGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.eps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::SetJointGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::SetJointGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.goal[i]);
    }
    s << indent << "eps: ";
    Printer<double>::stream(s, indent + "  ", v.eps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SETJOINTGOAL_H
