// Generated by gencpp from file arm_control/SetJointResult.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SETJOINTRESULT_H
#define ARM_CONTROL_MESSAGE_SETJOINTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct SetJointResult_
{
  typedef SetJointResult_<ContainerAllocator> Type;

  SetJointResult_()
    : result()
    , error(0.0)
    , time(0.0)
    , errorCode(0)  {
    }
  SetJointResult_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , error(0.0)
    , time(0.0)
    , errorCode(0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _result_type;
  _result_type result;

   typedef double _error_type;
  _error_type error;

   typedef double _time_type;
  _time_type time;

   typedef int32_t _errorCode_type;
  _errorCode_type errorCode;





  typedef boost::shared_ptr< ::arm_control::SetJointResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::SetJointResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointResult_

typedef ::arm_control::SetJointResult_<std::allocator<void> > SetJointResult;

typedef boost::shared_ptr< ::arm_control::SetJointResult > SetJointResultPtr;
typedef boost::shared_ptr< ::arm_control::SetJointResult const> SetJointResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::SetJointResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::SetJointResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control::SetJointResult_<ContainerAllocator1> & lhs, const ::arm_control::SetJointResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.error == rhs.error &&
    lhs.time == rhs.time &&
    lhs.errorCode == rhs.errorCode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control::SetJointResult_<ContainerAllocator1> & lhs, const ::arm_control::SetJointResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::SetJointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3234821a425afd21a836feedb269dec1";
  }

  static const char* value(const ::arm_control::SetJointResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3234821a425afd21ULL;
  static const uint64_t static_value2 = 0xa836feedb269dec1ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::SetJointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/SetJointResult";
  }

  static const char* value(const ::arm_control::SetJointResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::SetJointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"float64[] result\n"
"float64 error\n"
"float64 time\n"
"int32 errorCode\n"
;
  }

  static const char* value(const ::arm_control::SetJointResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::SetJointResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.error);
      stream.next(m.time);
      stream.next(m.errorCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::SetJointResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::SetJointResult_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.result[i]);
    }
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "errorCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errorCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SETJOINTRESULT_H
