// Generated by gencpp from file arm_control/SetJointFeedback.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SETJOINTFEEDBACK_H
#define ARM_CONTROL_MESSAGE_SETJOINTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct SetJointFeedback_
{
  typedef SetJointFeedback_<ContainerAllocator> Type;

  SetJointFeedback_()
    : positions()
    , error(0.0)
    , time(0.0)  {
    }
  SetJointFeedback_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , error(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _positions_type;
  _positions_type positions;

   typedef double _error_type;
  _error_type error;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::arm_control::SetJointFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::SetJointFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointFeedback_

typedef ::arm_control::SetJointFeedback_<std::allocator<void> > SetJointFeedback;

typedef boost::shared_ptr< ::arm_control::SetJointFeedback > SetJointFeedbackPtr;
typedef boost::shared_ptr< ::arm_control::SetJointFeedback const> SetJointFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::SetJointFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::SetJointFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control::SetJointFeedback_<ContainerAllocator1> & lhs, const ::arm_control::SetJointFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions &&
    lhs.error == rhs.error &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control::SetJointFeedback_<ContainerAllocator1> & lhs, const ::arm_control::SetJointFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetJointFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetJointFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetJointFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::SetJointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5ae14848692e7a0aae91af1c0a23e67";
  }

  static const char* value(const ::arm_control::SetJointFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5ae14848692e7a0ULL;
  static const uint64_t static_value2 = 0xaae91af1c0a23e67ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::SetJointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/SetJointFeedback";
  }

  static const char* value(const ::arm_control::SetJointFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::SetJointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float64[] positions\n"
"float64 error\n"
"float64 time\n"
;
  }

  static const char* value(const ::arm_control::SetJointFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::SetJointFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.error);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::SetJointFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::SetJointFeedback_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SETJOINTFEEDBACK_H
