// Generated by gencpp from file arm_control/SetPoseResult.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SETPOSERESULT_H
#define ARM_CONTROL_MESSAGE_SETPOSERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <arm_control/Pose.h>

namespace arm_control
{
template <class ContainerAllocator>
struct SetPoseResult_
{
  typedef SetPoseResult_<ContainerAllocator> Type;

  SetPoseResult_()
    : finalPose()
    , error(0.0)
    , time(0.0)
    , errorCode(0)  {
    }
  SetPoseResult_(const ContainerAllocator& _alloc)
    : finalPose(_alloc)
    , error(0.0)
    , time(0.0)
    , errorCode(0)  {
  (void)_alloc;
    }



   typedef  ::arm_control::Pose_<ContainerAllocator>  _finalPose_type;
  _finalPose_type finalPose;

   typedef double _error_type;
  _error_type error;

   typedef double _time_type;
  _time_type time;

   typedef int32_t _errorCode_type;
  _errorCode_type errorCode;





  typedef boost::shared_ptr< ::arm_control::SetPoseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::SetPoseResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetPoseResult_

typedef ::arm_control::SetPoseResult_<std::allocator<void> > SetPoseResult;

typedef boost::shared_ptr< ::arm_control::SetPoseResult > SetPoseResultPtr;
typedef boost::shared_ptr< ::arm_control::SetPoseResult const> SetPoseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::SetPoseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::SetPoseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control::SetPoseResult_<ContainerAllocator1> & lhs, const ::arm_control::SetPoseResult_<ContainerAllocator2> & rhs)
{
  return lhs.finalPose == rhs.finalPose &&
    lhs.error == rhs.error &&
    lhs.time == rhs.time &&
    lhs.errorCode == rhs.errorCode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control::SetPoseResult_<ContainerAllocator1> & lhs, const ::arm_control::SetPoseResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::SetPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetPoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SetPoseResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetPoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SetPoseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "335523dda63c3d3307109552301cda50";
  }

  static const char* value(const ::arm_control::SetPoseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x335523dda63c3d33ULL;
  static const uint64_t static_value2 = 0x07109552301cda50ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/SetPoseResult";
  }

  static const char* value(const ::arm_control::SetPoseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"arm_control/Pose finalPose\n"
"float64 error\n"
"float64 time\n"
"int32 errorCode\n"
"\n"
"================================================================================\n"
"MSG: arm_control/Pose\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64[] rotx\n"
"float64[] roty\n"
"float64[] rotz\n"
;
  }

  static const char* value(const ::arm_control::SetPoseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::SetPoseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finalPose);
      stream.next(m.error);
      stream.next(m.time);
      stream.next(m.errorCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPoseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::SetPoseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::SetPoseResult_<ContainerAllocator>& v)
  {
    s << indent << "finalPose: ";
    s << std::endl;
    Printer< ::arm_control::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.finalPose);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "errorCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errorCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SETPOSERESULT_H
