// Generated by gencpp from file arm_control/SolveFKPoseRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SOLVEFKPOSEREQUEST_H
#define ARM_CONTROL_MESSAGE_SOLVEFKPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct SolveFKPoseRequest_
{
  typedef SolveFKPoseRequest_<ContainerAllocator> Type;

  SolveFKPoseRequest_()
    : jointPositions()  {
    }
  SolveFKPoseRequest_(const ContainerAllocator& _alloc)
    : jointPositions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _jointPositions_type;
  _jointPositions_type jointPositions;





  typedef boost::shared_ptr< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SolveFKPoseRequest_

typedef ::arm_control::SolveFKPoseRequest_<std::allocator<void> > SolveFKPoseRequest;

typedef boost::shared_ptr< ::arm_control::SolveFKPoseRequest > SolveFKPoseRequestPtr;
typedef boost::shared_ptr< ::arm_control::SolveFKPoseRequest const> SolveFKPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::SolveFKPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control::SolveFKPoseRequest_<ContainerAllocator1> & lhs, const ::arm_control::SolveFKPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.jointPositions == rhs.jointPositions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control::SolveFKPoseRequest_<ContainerAllocator1> & lhs, const ::arm_control::SolveFKPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "730e1e3e6eb29501bae56546745b9c91";
  }

  static const char* value(const ::arm_control::SolveFKPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x730e1e3e6eb29501ULL;
  static const uint64_t static_value2 = 0xbae56546745b9c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/SolveFKPoseRequest";
  }

  static const char* value(const ::arm_control::SolveFKPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] jointPositions\n"
;
  }

  static const char* value(const ::arm_control::SolveFKPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointPositions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolveFKPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::SolveFKPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::SolveFKPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "jointPositions[]" << std::endl;
    for (size_t i = 0; i < v.jointPositions.size(); ++i)
    {
      s << indent << "  jointPositions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointPositions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SOLVEFKPOSEREQUEST_H
