// Generated by gencpp from file arm_control/SolveIKPose.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SOLVEIKPOSE_H
#define ARM_CONTROL_MESSAGE_SOLVEIKPOSE_H

#include <ros/service_traits.h>


#include <arm_control/SolveIKPoseRequest.h>
#include <arm_control/SolveIKPoseResponse.h>


namespace arm_control
{

struct SolveIKPose
{

typedef SolveIKPoseRequest Request;
typedef SolveIKPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIKPose
} // namespace arm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_control::SolveIKPose > {
  static const char* value()
  {
    return "71fc72fc4ceb6a49c53a3f29f5fe3527";
  }

  static const char* value(const ::arm_control::SolveIKPose&) { return value(); }
};

template<>
struct DataType< ::arm_control::SolveIKPose > {
  static const char* value()
  {
    return "arm_control/SolveIKPose";
  }

  static const char* value(const ::arm_control::SolveIKPose&) { return value(); }
};


// service_traits::MD5Sum< ::arm_control::SolveIKPoseRequest> should match
// service_traits::MD5Sum< ::arm_control::SolveIKPose >
template<>
struct MD5Sum< ::arm_control::SolveIKPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::SolveIKPose >::value();
  }
  static const char* value(const ::arm_control::SolveIKPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::SolveIKPoseRequest> should match
// service_traits::DataType< ::arm_control::SolveIKPose >
template<>
struct DataType< ::arm_control::SolveIKPoseRequest>
{
  static const char* value()
  {
    return DataType< ::arm_control::SolveIKPose >::value();
  }
  static const char* value(const ::arm_control::SolveIKPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_control::SolveIKPoseResponse> should match
// service_traits::MD5Sum< ::arm_control::SolveIKPose >
template<>
struct MD5Sum< ::arm_control::SolveIKPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::SolveIKPose >::value();
  }
  static const char* value(const ::arm_control::SolveIKPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::SolveIKPoseResponse> should match
// service_traits::DataType< ::arm_control::SolveIKPose >
template<>
struct DataType< ::arm_control::SolveIKPoseResponse>
{
  static const char* value()
  {
    return DataType< ::arm_control::SolveIKPose >::value();
  }
  static const char* value(const ::arm_control::SolveIKPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SOLVEIKPOSE_H
