// Generated by gencpp from file arm_control/SolveFKPose.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SOLVEFKPOSE_H
#define ARM_CONTROL_MESSAGE_SOLVEFKPOSE_H

#include <ros/service_traits.h>


#include <arm_control/SolveFKPoseRequest.h>
#include <arm_control/SolveFKPoseResponse.h>


namespace arm_control
{

struct SolveFKPose
{

typedef SolveFKPoseRequest Request;
typedef SolveFKPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveFKPose
} // namespace arm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_control::SolveFKPose > {
  static const char* value()
  {
    return "53d1373d894a3f3967818713171e9573";
  }

  static const char* value(const ::arm_control::SolveFKPose&) { return value(); }
};

template<>
struct DataType< ::arm_control::SolveFKPose > {
  static const char* value()
  {
    return "arm_control/SolveFKPose";
  }

  static const char* value(const ::arm_control::SolveFKPose&) { return value(); }
};


// service_traits::MD5Sum< ::arm_control::SolveFKPoseRequest> should match
// service_traits::MD5Sum< ::arm_control::SolveFKPose >
template<>
struct MD5Sum< ::arm_control::SolveFKPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::SolveFKPose >::value();
  }
  static const char* value(const ::arm_control::SolveFKPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::SolveFKPoseRequest> should match
// service_traits::DataType< ::arm_control::SolveFKPose >
template<>
struct DataType< ::arm_control::SolveFKPoseRequest>
{
  static const char* value()
  {
    return DataType< ::arm_control::SolveFKPose >::value();
  }
  static const char* value(const ::arm_control::SolveFKPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_control::SolveFKPoseResponse> should match
// service_traits::MD5Sum< ::arm_control::SolveFKPose >
template<>
struct MD5Sum< ::arm_control::SolveFKPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::SolveFKPose >::value();
  }
  static const char* value(const ::arm_control::SolveFKPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::SolveFKPoseResponse> should match
// service_traits::DataType< ::arm_control::SolveFKPose >
template<>
struct DataType< ::arm_control::SolveFKPoseResponse>
{
  static const char* value()
  {
    return DataType< ::arm_control::SolveFKPose >::value();
  }
  static const char* value(const ::arm_control::SolveFKPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SOLVEFKPOSE_H
